name: wedding
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # Localization
  intl: ^0.20.2

  # Styles
  google_fonts: ^6.2.1

  # State management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.0

  # Utilities
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.3.2

  # UI
  cached_network_image: ^3.4.1

  # Firebase
  firebase_core: ^4.4.0
  firebase_database: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0
  build_runner: ^2.5.2

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/webp/
    - assets/png/
    - assets/logo/
    - assets/icon/
    - assets/doc/